# Generated by Django 3.2 on 2021-05-07 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210507_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskfile',
            options={'verbose_name': 'Файл', 'verbose_name_plural': 'Файлы'},
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='task',
            new_name='File',
        ),
        migrations.RenameField(
            model_name='taskfile',
            old_name='title',
            new_name='FileTitle',
        ),
    ]
