# Generated by Django 3.2 on 2021-05-08 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210507_2023'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskModel2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='taskf',
            name='task',
            field=models.FileField(upload_to='documents/%Y/%m/%d'),
        ),
        migrations.AddField(
            model_name='taskmodel2',
            name='task',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.taskf'),
        ),
    ]
