# Generated by Django 3.2 on 2021-05-08 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210508_1523'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskmodel2',
            options={'verbose_name': 'Задача', 'verbose_name_plural': 'Задачи'},
        ),
        migrations.RenameField(
            model_name='taskf',
            old_name='task',
            new_name='task_1',
        ),
    ]
