# Generated by Django 3.2 on 2021-05-08 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20210508_1814'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='taskf',
            options={},
        ),
    ]
