# Generated by Django 3.2 on 2021-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='len_of_sentence',
        ),
        migrations.RemoveField(
            model_name='table',
            name='num_of_prep',
        ),
        migrations.RemoveField(
            model_name='table',
            name='part_of_speech',
        ),
        migrations.AlterField(
            model_name='table',
            name='len_of_words',
            field=models.FloatField(max_length=200),
        ),
        migrations.DeleteModel(
            name='TaskModel2',
        ),
    ]
