# Generated by Django 3.2 on 2021-05-10 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20210510_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='len_of_sentence',
            field=models.FloatField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep',
            field=models.FloatField(default=None, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech',
            field=models.FloatField(default=None, max_length=200),
            preserve_default=False,
        ),
    ]
