# Generated by Django 3.2 on 2021-05-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210510_1547'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableAuthors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('surname', models.CharField(max_length=200, verbose_name='фамилия')),
                ('len_of_sentence', models.FloatField(max_length=200, verbose_name='Средняя длина предложения')),
                ('len_of_words', models.FloatField(max_length=200, verbose_name='Средняя длина слова')),
                ('num_of_prep_a', models.IntegerField(max_length=200, verbose_name='Количество ...')),
                ('num_of_prep_b', models.IntegerField(max_length=200, verbose_name='Количество !..')),
                ('num_of_prep_c', models.IntegerField(max_length=200, verbose_name='Количество ?..')),
                ('num_of_prep_d', models.IntegerField(max_length=200, verbose_name='Количество !')),
                ('num_of_prep_e', models.IntegerField(max_length=200, verbose_name='Количество ?')),
                ('num_of_prep_f', models.IntegerField(max_length=200, verbose_name='Количество .')),
                ('num_of_prep_g', models.IntegerField(max_length=200, verbose_name='Количество ,')),
                ('num_of_prep_h', models.IntegerField(max_length=200, verbose_name='Количество ;')),
                ('num_of_prep_i', models.IntegerField(max_length=200, verbose_name='Количество :')),
                ('part_of_speech_a', models.IntegerField(max_length=200, verbose_name='Количество существительных')),
                ('part_of_speech_b', models.IntegerField(max_length=200, verbose_name='Количество глаголов')),
                ('part_of_speech_c', models.IntegerField(max_length=200, verbose_name='Количество прлагательное')),
                ('part_of_speech_d', models.IntegerField(max_length=200, verbose_name='Количество наречие')),
                ('part_of_speech_e', models.IntegerField(max_length=200, verbose_name='Количество причастие')),
                ('part_of_speech_f', models.IntegerField(max_length=200, verbose_name='Количество деепричастие')),
            ],
        ),
        migrations.RemoveField(
            model_name='table',
            name='num_of_prep',
        ),
        migrations.RemoveField(
            model_name='table',
            name='part_of_speech',
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_a',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество ...'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_b',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество !..'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_c',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество ?..'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_d',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество !'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_e',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество ?'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_f',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество .'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_g',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество ,'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_h',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество ;'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='num_of_prep_i',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество :'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_a',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество существительных'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_b',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество глаголов'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_c',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество прлагательное'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_d',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество наречие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_e',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество причастие'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='part_of_speech_f',
            field=models.IntegerField(default=None, max_length=200, verbose_name='Количество деепричастие'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='table',
            name='len_of_sentence',
            field=models.FloatField(max_length=200, verbose_name='Средняя длина предложения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='len_of_words',
            field=models.FloatField(max_length=200, verbose_name='Средняя длина слова'),
        ),
        migrations.AlterField(
            model_name='table',
            name='surname',
            field=models.CharField(max_length=200, verbose_name='фамилия'),
        ),
    ]
