# Generated by Django 3.2 on 2021-05-10 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210510_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='len_of_sentence',
            field=models.FloatField(verbose_name='Средняя длина предложения'),
        ),
        migrations.AlterField(
            model_name='table',
            name='len_of_words',
            field=models.FloatField(verbose_name='Средняя длина слова'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_a',
            field=models.IntegerField(verbose_name='Количество "..." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_b',
            field=models.IntegerField(verbose_name='Количество "!.." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_c',
            field=models.IntegerField(verbose_name='Количество "?.." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_d',
            field=models.IntegerField(verbose_name='Количество "!" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_e',
            field=models.IntegerField(verbose_name='Количество "?" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_f',
            field=models.IntegerField(verbose_name='Количество "." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_g',
            field=models.IntegerField(verbose_name='Количество "," :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_h',
            field=models.IntegerField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_i',
            field=models.IntegerField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_a',
            field=models.FloatField(verbose_name='Количество существительных'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_b',
            field=models.FloatField(verbose_name='Количество глаголов'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_c',
            field=models.FloatField(verbose_name='Количество прлагательных'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_d',
            field=models.FloatField(verbose_name='Количество наречий'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_e',
            field=models.FloatField(verbose_name='Количество причастий'),
        ),
        migrations.AlterField(
            model_name='table',
            name='part_of_speech_f',
            field=models.FloatField(verbose_name='Количество деепричастий'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='len_of_sentence',
            field=models.FloatField(verbose_name='Средняя длина предложения'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='len_of_words',
            field=models.FloatField(verbose_name='Средняя длина слова'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_a',
            field=models.IntegerField(verbose_name='Количество "..." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_b',
            field=models.IntegerField(verbose_name='Количество "!.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_c',
            field=models.IntegerField(verbose_name='Количество "?.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_d',
            field=models.IntegerField(verbose_name='Количество "!" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_e',
            field=models.IntegerField(verbose_name='Количество "?" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_f',
            field=models.IntegerField(verbose_name='Количество "." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_g',
            field=models.IntegerField(verbose_name='Количество "," :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_h',
            field=models.IntegerField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_i',
            field=models.IntegerField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_a',
            field=models.FloatField(verbose_name='Количество существительных'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_b',
            field=models.FloatField(verbose_name='Количество глаголов'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_c',
            field=models.FloatField(verbose_name='Количество прлагательных'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_d',
            field=models.FloatField(verbose_name='Количество наречий'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_e',
            field=models.FloatField(verbose_name='Количество причастий'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_f',
            field=models.FloatField(verbose_name='Количество деепричастий'),
        ),
    ]
