# Generated by Django 3.2 on 2021-05-10 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_auto_20210510_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_a',
            field=models.IntegerField(verbose_name='Среднее количество "..." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_b',
            field=models.IntegerField(verbose_name='Среднее количество "!.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_c',
            field=models.IntegerField(verbose_name='Среднее количество "?.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_d',
            field=models.IntegerField(verbose_name='Среднее количество "!" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_e',
            field=models.IntegerField(verbose_name='Среднее количество "?" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_f',
            field=models.IntegerField(verbose_name='Среднее количество "." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_g',
            field=models.IntegerField(verbose_name='Среднее количество "," :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_h',
            field=models.IntegerField(verbose_name='Среднее количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_i',
            field=models.IntegerField(verbose_name='Среднее количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_a',
            field=models.FloatField(verbose_name='Среднее количество существительных'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_b',
            field=models.FloatField(verbose_name='Среднее количество глаголов'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_c',
            field=models.FloatField(verbose_name='Среднее количество прлагательных'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_d',
            field=models.FloatField(verbose_name='Среднее количество наречий'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_e',
            field=models.FloatField(verbose_name='Среднее количество причастий'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='part_of_speech_f',
            field=models.FloatField(verbose_name='Среднее количество деепричастий'),
        ),
    ]
