# Generated by Django 3.2 on 2021-05-11 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20210510_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_a',
            field=models.FloatField(verbose_name='Количество "..." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_b',
            field=models.FloatField(verbose_name='Количество "!.." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_c',
            field=models.FloatField(verbose_name='Количество "!" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_d',
            field=models.FloatField(verbose_name='Количество "!" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_e',
            field=models.FloatField(verbose_name='Количество "?" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_f',
            field=models.FloatField(verbose_name='Количество "." :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_g',
            field=models.FloatField(verbose_name='Количество "," :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_h',
            field=models.FloatField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='table',
            name='num_of_prep_i',
            field=models.FloatField(verbose_name='Количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_a',
            field=models.FloatField(verbose_name='Среднее количество "..." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_b',
            field=models.FloatField(verbose_name='Среднее количество "!.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_c',
            field=models.FloatField(verbose_name='Среднее количество "?.." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_d',
            field=models.FloatField(verbose_name='Среднее количество "!" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_e',
            field=models.FloatField(verbose_name='Среднее количество "?" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_f',
            field=models.FloatField(verbose_name='Среднее количество "." :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_g',
            field=models.FloatField(verbose_name='Среднее количество "," :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_h',
            field=models.FloatField(verbose_name='Среднее количество ":" :'),
        ),
        migrations.AlterField(
            model_name='tableauthors',
            name='num_of_prep_i',
            field=models.FloatField(verbose_name='Среднее количество ":" :'),
        ),
    ]
